In [14]:
import numpy as np


In [15]:
list1=[[2,4,6,8,10],[1,3,5,7,9]]

In [16]:
arr1=np.array(list1)
arr1

array([[ 2,  4,  6,  8, 10],
       [ 1,  3,  5,  7,  9]])

In [17]:
arr2=np.array(list1,dtype='bool')
arr2

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [18]:
arr3=np.array([2,4,5,6,'chhhh'],dtype='object')
arr3

array([2, 4, 5, 6, 'chhhh'], dtype=object)

In [19]:
list3=arr3.tolist()
list3

[2, 4, 5, 6, 'chhhh']

In [20]:
arr1.shape

(2, 5)

In [21]:
arr2.size

10

In [22]:
arr2.ndim

2

**REVERSING ROWS ANDFD COLOUMNS

In [24]:
list4=[[2,4,6,8,10],[1,3,5,7,9]]
arr4=np.array(list4)
arr4

array([[ 2,  4,  6,  8, 10],
       [ 1,  3,  5,  7,  9]])

In [25]:
arr4[::-1]

array([[ 1,  3,  5,  7,  9],
       [ 2,  4,  6,  8, 10]])

In [26]:
arr4[-1::]

array([[1, 3, 5, 7, 9]])

In [27]:
arr4.T

array([[ 2,  1],
       [ 4,  3],
       [ 6,  5],
       [ 8,  7],
       [10,  9]])

In [29]:
arr4[::-1,::-1]

array([[ 9,  7,  5,  3,  1],
       [10,  8,  6,  4,  2]])

**BASIC SYNTEX**

In [32]:
arr4.min()

1

In [33]:
arr4.max()

10

In [35]:
arr4.mean()

5.5

In [36]:
np.median(arr4)

5.5

In [37]:
np.var(arr4)

8.25

**RESHAPING AND FLATENING**

In [41]:
arr4.reshape(10,1)

array([[ 2],
       [ 4],
       [ 6],
       [ 8],
       [10],
       [ 1],
       [ 3],
       [ 5],
       [ 7],
       [ 9]])

In [45]:
f1=arr4.flatten()
f1

array([ 2,  4,  6,  8, 10,  1,  3,  5,  7,  9])

In [43]:
arr4.ndim

2

In [44]:
f1.ndim

1

__RANDOM ARRAY__

In [46]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
np.arange(2,10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
np.arange(2,10,2)

array([2, 4, 6, 8])

In [52]:
np.arange(10,0,-1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [53]:
np.linspace(1,10,3)

array([ 1. ,  5.5, 10. ])

In [56]:
np.zeros([2,2])

array([[0., 0.],
       [0., 0.]])

In [61]:
np.zeros_like(np.arange(3))

array([0, 0, 0])

In [63]:
np.ones(np.arange(3))

array([], shape=(0, 1, 2), dtype=float64)

**UNIQUE ITEMS AND COUNTS**

In [64]:
arr5=[[1,2,3,4,5,6],[3,4,2,2,3,5]]

In [67]:
unq=np.unique(arr5,return_counts=True)

In [68]:
unq

(array([1, 2, 3, 4, 5, 6]), array([1, 3, 3, 2, 2, 1], dtype=int64))